### ISSUE TITLE
IE11 fromJS bug 

### ISSUE THREAD

**Issue by Methuselah96** [immutable-js-oss/immutable-js#110]
*From @rytisbac on Wed, 14 Nov 2018 07:57:33 GMT*

Version v4.0.0-rc.12 
Function fromJS. 
example:
`console.log(fromJS({test: 'qqq'}))`
In most of the browsers it returns Map object, but IE11 returns the same object. 
Other case:
`console.log(fromJS([{test: 'qqq'}]))`
In most of the browsers it returns List and Map as first element, but IE11 returns List and initial object. 

Version 3.8.2 works as expected

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1648*

**Comment by Methuselah96** [comment]
Related: https://github.com/immutable-js/immutable-js/issues/1745

**Comment by jdeniau** [comment]
This is fixed on master:

Tried on IE11 on immutable doc website:
![image](https://user-images.githubusercontent.com/1398469/100517157-122aaf80-3189-11eb-9d5e-fb7c5a39263d.png)

And with build version of master:
![image](https://user-images.githubusercontent.com/1398469/100517167-1d7ddb00-3189-11eb-82f4-fd44dd4e6bc6.png)

**Comment by Methuselah96** [comment]
Thanks!
