### ISSUE TITLE
`updateIn` doesn't properly handle `notSetValue`

### ISSUE THREAD

**Issue by Methuselah96** [immutable-js-oss/immutable-js#113]
*From @migueloller on Fri, 30 Nov 2018 21:50:42 GMT*

### What happened

`updateIn` doesn't properly handle `notSetValue`.

### How to reproduce

```es6
const { updateIn } = require('immutable')
const original = { x: { y: { z: 123 } } }
const NOT_SET = { NOT_SET: true }
console.log(updateIn(original, ['x', 'y'], NOT_SET, val => NOT_SET)) // { x: { y: { NOT_SET: true } } }
```

Expected the log output to be `{ x: {} }` instead. Is this intended behavior?

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1657*

**Comment by Methuselah96** [comment]
Correct behavior.

**Comment by migueloller** [comment]
@Methuselah96, how is this correct behavior? If the updater returns the "not set" value, then the value at that key should be unset (i.e., removed).

**Comment by migueloller** [comment]
For any future readers, explanation is here: https://github.com/immutable-js/immutable-js/issues/1657#issuecomment-731459727

**Comment by migueloller** [comment]
Based on the implementation at https://github.com/immutable-js-oss/immutable-js/blob/7a79603dbdfad44bdf41b4fd73334dce90f9ce64/src/functional/updateIn.js#L31, it seems that `notSetValue` is returned back to the `updateIn` caller if the value itself is not set. So it seems that it is not just limited to the value passed to the updater function if there is no value at the key path.
