### ISSUE TITLE
[Bug] isPlainObj fn not compatible for IE11

### ISSUE THREAD

**Issue by Methuselah96** [immutable-js-oss/immutable-js#159]
*From @binarykitchen on Thu, 31 Oct 2019 02:53:06 GMT*

This implementation is breaking on IE11

```
  function isPlainObj(value) {
    return (
      value &&
      (typeof value.constructor !== 'function' ||
        value.constructor.name === 'Object')
    );
  }
```

Always returns false.

Refer to https://stackoverflow.com/questions/25140723/constructor-name-is-undefined-in-internet-explorer

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1745*

**Comment by Methuselah96** [comment]
Related:
https://github.com/immutable-js/immutable-js/issues/1648

**Comment by bdurrer** [comment]
The current function also fails to correctly detect objects which have property 'constructor' that has a property 'name':
```
// will return false
isPlainObj({ constructor: { name: 'bamboozled' }});
```
