### ISSUE TITLE
List.merge is not an alias to List.concat

### ISSUE THREAD

**Issue by claweyenuk** [immutable-js-oss/immutable-js#221]
### What happened

This is a tiny change in the docs but did not see where it was generated.

Under List.concat, the documentation includes "merge" as an alias. This is incorrect - merge will merge the elements in the List, not concatenate 2 lists. (Discovered while debugging some code)

**Comment by Methuselah96** [comment]
I don't understand the difference between the two things you said, but it seems like `merge` is just a reference to `concat` based on the code: https://github.com/immutable-js-oss/immutable-js/blob/master/src/List.js#L249.

**Comment by claweyenuk** [comment]
Ah, I see the issue. Sorry for the confusion, I'll close the issue

I am on 3.8.2, the docs are 4.x. In 3.8.2 it was different (https://github.com/immutable-js/immutable-js/blob/9e886489b3af4a9f327a5f71a1819dfb8517c025/src/List.js#L129)

List.merge in 3.x merges the lists element by element. So list A[0] is merged with list B[0], A[1] with B[1], etc..
