### ISSUE TITLE
Merge back to immutable-js repo

### ISSUE THREAD

**Issue by conartist6** [immutable-js-oss/immutable-js#222]
Now that we have perms on the main repo, we need to merge this code back into the mainline and decommission this repo. I think the code should merge cleanly, but the issues will take some manual sorting out I suspect. I see that @Methuselah96 has already started on that.

**Comment by jdeniau** [comment]
Done ! \o/ 
I think we can delete this repository now.

**Comment by conartist6** [comment]
Wow, thanks so much for all that work!

**Comment by jdeniau** [comment]
@conartist6  Apparently, you are not on the [maintainer team](https://github.com/orgs/immutable-js/teams/maintainers/members) of immutable-js. Did you receive an invitation ?

**Comment by conartist6** [comment]
Oops, I guess I did but I didn't realize it. I forgot github works like that.

I'm going to archive this repo... What should we do with issues here? Should we close them?

**Comment by Methuselah96** [comment]
I would just leave them as they are and archive the repo along with a note in the README.

**Comment by Methuselah96** [comment]
Done in https://github.com/immutable-js/immutable-js/pull/1833.
