### ISSUE TITLE
setIn not existent array index inside Map raise exception

### ISSUE THREAD

**Issue by Methuselah96** [immutable-js-oss/immutable-js#54]
*From @rogeliotg on Fri, 27 Oct 2017 17:15:39 GMT*

My problem is, using inmutable in this structure:

myMap = Map({a: [], b: []});
myMAp.setIn(['a', 0], 'v');
this is getting an exception

immutable.js:870 Uncaught (in promise) Error: invalid keyPath
    at invariant (immutable.js:870)
    at updateInDeepMap (immutable.js:1974)
    at updateInDeepMap (immutable.js:1980)
    at Map.updateIn (immutable.js:1278)
    at Map.setIn (immutable.js:1256)
I know I can check if such index exist, initialize if not, then try the update, but maybe a feature request is feasible so inmutable let do this on one step. I don't see any motive for inmutable raising an exception on this use case. I'm reading the library spec on http://untangled.io/immutable-js-all-the-examples-youll-ever-need-to-get-set-and-delete-data-from-lists/ And what I propose is what is normal on lists:

If an index doesn’t exist anywhere in the keyPath, then List.setin() will do one of the following:

If the index preceding the bad index references a List, then the bad index is trying to insert a value at a place outside of the bounds of this list. Usual rules apply, and the List expands, the value is placed at the end of the expanded List, and nulls are inserted in between. Try it for yourself in the example below, by replacing the last line with avengersList.setIn([1, 1, 1, 3], 'scarletWitch'); If the index preceding the bad index is a value (i.e. not a List or Map), then the bad index is trying to insert a value into a data type that has no concept of an index; accordingly, an Invalid keyPath error will be thrown. Try it for yourself in the example below, by replacing the last line with avengersList.setIn([0, 1], 'scarletWitch');. This tries to insert ‘scarletWitch’ into the String ‘ironMan’, and that’s never going to work!

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1428*

**Comment by Methuselah96** [comment]
The behavior changed for this example. It threw an error in 3.x, but now it does not in 4.x. I'm not sure if that's intentional or not.

**Comment by Methuselah96** [comment]
Taking this off the milestone since I don't think this is a common use case. Probably should just be using a `List` anyway.

**Comment by Methuselah96** [comment]
According to the docs "If any keys in keyPath do not exist, a new immutable Map will be created at that key." which is not what's happening (it's not throwing an Error now either).

https://codesandbox.io/s/lucid-wu-c5fb9?file=/src/index.js

**Comment by jdeniau** [comment]
@Methuselah96 in your example you do test the initial input, not the updated Map.

I added a PR to check that everything works correcly (and even better than I expected !)

**Comment by Methuselah96** [comment]
Good catch, thanks.
