### ISSUE TITLE
List.delete() sets element to empty array instead of removing it

### ISSUE THREAD

**Issue by Methuselah96** [immutable-js-oss/immutable-js#69]
*From @lpatalas on Sun, 14 Jan 2018 09:51:15 GMT*

Hello.

I'm using Immutable.js v4.0.0-rc.9 with react-native v0.50.4.

If I run the following code snippet:
```
const list1 = List.of(1, 2, 3);
const list2 = list1.delete(1);
console.log(`list1`, list1.size, list1);
console.log(`list2`, list2.size, list2);
```

I get this output in the console:

```
01-14 10:22:26.568  4347  4982 I ReactNativeJS: 'list1', 3, { size: 3,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _origin: 0,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _capacity: 3,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _level: 5,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _root: null,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _tail: { array: [ 1, 2, 3 ], ownerID: undefined },
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   __ownerID: undefined,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   __hash: undefined,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   __altered: false }
01-14 10:22:26.568  4347  4982 I ReactNativeJS: 'list2', 3, { size: 3,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _origin: 0,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _capacity: 3,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _level: 5,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _root: null,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   _tail: { array: [ 1, [], 3 ], ownerID: {} },
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   __ownerID: undefined,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   __hash: undefined,
01-14 10:22:26.568  4347  4982 I ReactNativeJS:   __altered: false }
```

So basically it seems that the element is replaced by empty array instead of being removed from collection. It only happens when running without debugger attached, so I guess it may be dependent on JS engine.

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1474*

**Comment by Methuselah96** [comment]
This is an issue in IE11 as well. Check to make sure https://github.com/immutable-js-oss/immutable-js/pull/194 doesn't fix it.

**Comment by jdeniau** [comment]
@Methuselah96 Seems to be fixes, see #203

**Comment by Methuselah96** [comment]
This is an IE11 issue. Can you make sure it's fixed on IE11 as well?

**Comment by jdeniau** [comment]
It is fixed too.

With immutable 4.0.0-rc.12:
![image](https://user-images.githubusercontent.com/1398469/100711351-75972600-33b1-11eb-8c7c-33ab6279f37c.png)

Issue with `delete` and `List.of`

On master branch:
![image](https://user-images.githubusercontent.com/1398469/100711421-89db2300-33b1-11eb-8536-8cf6c61ebf18.png)

Both `List.of` and `delete` works as expected

**Comment by Methuselah96** [comment]
Thanks!
