### ISSUE TITLE
`clear()` doesn't return to default values

### ISSUE THREAD

**Issue by Methuselah96** [immutable-js-oss/immutable-js#85]
*From @lovincyrus on Wed, 01 Aug 2018 07:36:11 GMT*

### What happened

Issue with `clear()` — https://facebook.github.io/immutable-js/docs/#/Record/clear

When `clear()`, it doesn't return to its default values.

### How to reproduce

```
const User = Record({
  roles: List()
})

const assertEqual = (a, b) => {
  if (a.equals(b)) return true
  throw new Error('Failed equality check')
}

const user_0 = new User({ roles: ['superuser', 'admin'] })
const user_1 = user_0.clear();

assertEqual(user_1.roles, List())

const user_3 = user_0.withMutations(mutable => mutable.reset())

assertEqual(user_3.roles, List())
```

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1565*

**Comment by jdeniau** [comment]
Apparently it does work. I do not understand the user_3 "reset" call though as `reset` is nor a `List`, nor an array API
