### ISSUE TITLE
The doc(generated) of `updateIn` gives wrong code sample.

### ISSUE THREAD

**Issue by Methuselah96** [immutable-js-oss/immutable-js#89]
*From @coolgod on Tue, 21 Aug 2018 23:17:40 GMT*

https://facebook.github.io/immutable-js/docs/#/updateIn

the code example says `setIn`, it should use `updateIn`

can't tell what's going wrong with a quick look, maybe needs a redeployment for the website with a newer version?
https://github.com/facebook/immutable-js/blob/master/type-definitions/Immutable.d.ts#L5119

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1579*

**Comment by coolgod** [comment]
I closed my original issue. I believe somehow it's fixed. So feel free to close this one also.

**Comment by Methuselah96** [comment]
Thanks!
