### ISSUE TITLE
OrderedSet subtract returning incorrect result when last remove resizes internal list

### ISSUE THREAD

**Issue by Methuselah96** [immutable-js-oss/immutable-js#96]
*From @heirendtm on Thu, 20 Sep 2018 00:49:11 GMT*

It looks like this occurs as of "immutable": "4.0.0-rc.5". Calling subtract on an OrderedSet fails in some cases, and instead returns the original OrderedSet with no items removed. Specifically, if the internal _list happens to be resized on the final remove, it loses the _altered=true flag. Since the internal _list looks unaltered, the subtract function just returns the original OrderedSet.

Try it here: https://codesandbox.io/s/1op9o9475q 

Suspect line is here: https://github.com/facebook/immutable-js/blob/f71ccd5db2016e0dbed72838ab81b931b5e90e9e/src/OrderedMap.js#L139

newList is created containing the correct entries, but on this line the _altered of the newList is false which carries forward to the subsequent checks for if the subtract altered the OrderedSet.  Before that line, list has the altered=true flag. After that, newList has altered=false, and it never gets reset to true since no other items are removed.

*Copied from original issue: https://github.com/immutable-js/immutable-js/issues/1603*

**Comment by Methuselah96** [comment]
May be a duplicate of https://github.com/immutable-js-oss/immutable-js/issues/139.

**Comment by jdeniau** [comment]
Apparently fixed. See #198
